//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JahresUrlaub.Web
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Benutzer
    {
        [Required(ErrorMessage ="Das Feld ist Erfolgreich")]
        public int Benutzer_id { get; set; }
        [Required(ErrorMessage = "Das Feld ist Erfolgreich")]
        public string Personalnummer { get; set; }
        [Required(ErrorMessage = "Das Feld ist Erfolgreich")]
        public string Vorname { get; set; }
        [Required(ErrorMessage = "Das Feld ist Erfolgreich")]
        public string Nachname { get; set; }
        [Required(ErrorMessage = "Das Feld ist Erfolgreich")]
        public string Username { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Das Feld ist Erfolgreich")]
        public string passwordUser { get; set; }
        [Required(ErrorMessage = "Das Feld ist Erfolgreich")]
        public string Abteilung { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
