//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPlatfform.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotiId { get; set; }
        public Nullable<int> FromUserId { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public string NotiHeader { get; set; }
        public string NotiBody { get; set; }
        public Nullable<bool> isRead { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
